#server.port=
#
#spring.datasource.driver-class-name=
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
#
#email.sender =
#email.password =
#email.smtpHost =
#email.smtpPort =
#email.emailSignature =
